"""
Dummy File Generator for Pattern Testing

Generates realistic dummy video and subtitle files for all 30 episode patterns.
Files are minimal (1KB) but have valid structure for testing pattern matching.

Usage:
    python tests/generate_test_files.py

Output:
    tests/fixtures/pattern_files/pattern_##_<name>/
        ├── <video_variation_1>.mkv
        ├── <video_variation_2>.mkv
        ├── <subtitle_variation_1>.srt
        ├── <subtitle_variation_2>.srt
        └── ...

Version: 3.2.0
"""

import json
import sys
from pathlib import Path


def extract_extensions_from_definitions(pattern_file: Path) -> dict:
    """
    Extract all unique file extensions from pattern_definitions.json.
    
    Args:
        pattern_file: Path to pattern_definitions.json
    
    Returns:
        Dictionary with 'video' and 'subtitle' extension sets
        Example: {'video': {'.mkv', '.mp4'}, 'subtitle': {'.srt', '.ass'}}
    """
    try:
        with open(pattern_file, 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        video_exts = set()
        subtitle_exts = set()
        
        for pattern in data.get('patterns', []):
            for variation in pattern.get('variations', []):
                # Extract video extension
                video_template = variation.get('video_template', '')
                if video_template:
                    video_ext = Path(video_template).suffix.lower()
                    if video_ext:
                        video_exts.add(video_ext)
                
                # Extract subtitle extension
                subtitle_template = variation.get('subtitle_template', '')
                if subtitle_template:
                    subtitle_ext = Path(subtitle_template).suffix.lower()
                    if subtitle_ext:
                        subtitle_exts.add(subtitle_ext)
        
        return {
            'video': video_exts,
            'subtitle': subtitle_exts
        }
    
    except Exception as e:
        print(f"[WARNING] Failed to extract extensions: {e}")
        # Fallback to common extensions
        return {
            'video': {'.mkv', '.mp4'},
            'subtitle': {'.srt', '.ass'}
        }


def create_dummy_video(filepath: Path, size_kb: int = 1):
    """
    Create a minimal dummy video file (supports .mkv, .mp4, etc.).
    
    Args:
        filepath: Path where the video file should be created
        size_kb: Target file size in KB (default: 1KB)
    """
    # Create minimal valid headers for different formats
    # For testing purposes, we just need files with valid extensions
    # Real headers would be complex, but pattern matching only checks filenames
    
    extension = filepath.suffix.lower()
    
    if extension == '.mkv':
        header = b'\x1a\x45\xdf\xa3'  # EBML header signature
    elif extension == '.mp4':
        # Minimal MP4 header (ftyp box)
        header = b'\x00\x00\x00\x20\x66\x74\x79\x70\x69\x73\x6f\x6d'
    else:
        # Generic header for other formats
        header = b'\x00\x00\x00\x01'
    
    # Pad to reach target size
    content = header + b'\x00' * (size_kb * 1024 - len(header))
    
    filepath.parent.mkdir(parents=True, exist_ok=True)
    with open(filepath, 'wb') as f:
        f.write(content)


def create_dummy_subtitle(filepath: Path, size_kb: int = 1):
    """
    Create a minimal dummy subtitle file (supports .srt, .ass, etc.).
    
    Args:
        filepath: Path where the subtitle file should be created
        size_kb: Target file size in KB (default: 1KB)
    """
    extension = filepath.suffix.lower()
    
    if extension == '.srt':
        # Create valid SRT format content
        base_content = """1
00:00:01,000 --> 00:00:05,000
This is a dummy subtitle file for pattern testing.

2
00:00:05,000 --> 00:00:10,000
Pattern matching only checks filenames, not content.

3
00:00:10,000 --> 00:00:15,000
Generated by SubFast v3.2.0 test suite.

"""
    elif extension == '.ass':
        # Create valid ASS format content
        base_content = """[Script Info]
Title: SubFast Test Subtitle
ScriptType: v4.00+

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:01.00,0:00:05.00,Default,,0,0,0,,This is a dummy ASS subtitle for pattern testing.
Dialogue: 0,0:00:05.00,0:00:10.00,Default,,0,0,0,,Pattern matching only checks filenames, not content.
Dialogue: 0,0:00:10.00,0:00:15.00,Default,,0,0,0,,Generated by SubFast v3.2.0 test suite.

"""
    else:
        # Generic subtitle format
        base_content = "Dummy subtitle content for testing.\nPattern matching only checks filenames.\n\n"
    
    # Repeat content to reach target size
    content = base_content
    while len(content.encode('utf-8')) < size_kb * 1024:
        content += base_content
    
    filepath.parent.mkdir(parents=True, exist_ok=True)
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)


def generate_pattern_files(pattern: dict, base_dir: Path) -> tuple:
    """
    Generate dummy files for a single pattern with [VAR#] prefixes.
    
    Args:
        pattern: Pattern definition from JSON (new VAR-based structure)
        base_dir: Base directory for pattern files
    
    Returns:
        Tuple of (videos_created, subtitles_created)
    """
    pattern_id = pattern['id']
    pattern_name = pattern['name'].replace('##', '').replace('#', '').replace(' ', '_').strip('_')
    
    # Create pattern directory
    pattern_dir = base_dir / f"pattern_{pattern_id:02d}_{pattern_name}"
    pattern_dir.mkdir(parents=True, exist_ok=True)
    
    videos_created = 0
    subtitles_created = 0
    
    # Generate files for each variation
    for variation in pattern.get('variations', []):
        var_id = variation['var_id']  # e.g., "VAR1"
        video_template = variation['video_template']
        subtitle_template = variation['subtitle_template']
        
        # Add [VAR#] prefix to filenames
        video_filename = f"[{var_id}]-{video_template}"
        subtitle_filename = f"[{var_id}]-{subtitle_template}"
        
        # Generate video file
        video_path = pattern_dir / video_filename
        create_dummy_video(video_path)
        videos_created += 1
        
        # Generate subtitle file
        subtitle_path = pattern_dir / subtitle_filename
        create_dummy_subtitle(subtitle_path)
        subtitles_created += 1
    
    return (videos_created, subtitles_created)


def generate_all_pattern_files():
    """
    Main function: Read pattern definitions and generate all dummy files.
    """
    # Determine script location and project root
    script_dir = Path(__file__).parent
    project_root = script_dir.parent
    
    # Load pattern definitions
    pattern_file = script_dir / 'fixtures' / 'pattern_definitions.json'
    
    if not pattern_file.exists():
        print(f"[ERROR] Pattern definitions file not found: {pattern_file}")
        print("Please ensure tests/fixtures/pattern_definitions.json exists.")
        sys.exit(1)
    
    with open(pattern_file, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    patterns = data.get('patterns', [])
    
    if not patterns:
        print("[ERROR] No patterns found in pattern_definitions.json")
        sys.exit(1)
    
    # Create base directory for pattern files
    base_dir = script_dir / 'fixtures' / 'pattern_files'
    base_dir.mkdir(parents=True, exist_ok=True)
    
    # Statistics
    total_videos = 0
    total_subtitles = 0
    patterns_processed = 0
    
    # Extract and display detected extensions
    detected_exts = extract_extensions_from_definitions(pattern_file)
    
    print("=" * 80)
    print("SubFast v3.2.0 - Dummy File Generator for Pattern Testing")
    print("=" * 80)
    print(f"\nBase directory: {base_dir}")
    print(f"Total patterns to process: {len(patterns)}")
    print(f"Detected video extensions: {', '.join(sorted(detected_exts['video']))}")
    print(f"Detected subtitle extensions: {', '.join(sorted(detected_exts['subtitle']))}\n")
    
    # Generate files for each pattern
    for pattern in patterns:
        pattern_id = pattern['id']
        pattern_name = pattern['name']
        
        try:
            videos, subtitles = generate_pattern_files(pattern, base_dir)
            total_videos += videos
            total_subtitles += subtitles
            patterns_processed += 1
            
            print(f"[OK] Pattern {pattern_id:02d}: {pattern_name:<20} "
                  f"({videos} videos, {subtitles} subtitles)")
        
        except Exception as e:
            print(f"[FAIL] Pattern {pattern_id:02d}: {pattern_name:<20} FAILED - {e}")
    
    # Summary
    print("\n" + "=" * 80)
    print("GENERATION SUMMARY")
    print("=" * 80)
    print(f"Patterns processed:    {patterns_processed}/{len(patterns)}")
    print(f"Video files created:   {total_videos}")
    print(f"Subtitle files created: {total_subtitles}")
    print(f"Total files created:   {total_videos + total_subtitles}")
    print("=" * 80)
    
    if patterns_processed == len(patterns):
        print("\n[SUCCESS] All pattern files generated successfully!")
        return 0
    else:
        print(f"\n[ERROR] Some patterns failed. Check errors above.")
        return 1


if __name__ == '__main__':
    sys.exit(generate_all_pattern_files())
